"""Shared taxonomies and weights for JD parsing and candidate feature extraction."""

from __future__ import annotations

PROFICIENCY_WEIGHT: dict[str, float] = {
    "beginner": 0.25,
    "intermediate": 0.5,
    "advanced": 0.75,
    "expert": 1.0,
}

SENIORITY_KEYWORDS: dict[str, list[str]] = {
    "junior": ["junior", "entry", "associate", "graduate", "intern"],
    "mid": ["engineer", "developer", "analyst", "scientist"],
    "senior": ["senior", "sr.", "sr ", "lead", "staff", "principal"],
    "lead": ["tech lead", "team lead", "engineering manager", "head of"],
}

ROLE_FAMILY_PATTERNS: dict[str, list[str]] = {
    "ml_engineer": [
        "machine learning engineer",
        "ml engineer",
        "applied scientist",
        "applied ml",
    ],
    "ai_engineer": [
        "ai engineer",
        "artificial intelligence",
        "genai engineer",
    ],
    "nlp_engineer": [
        "nlp engineer",
        "nlp scientist",
        "language model",
        "llm engineer",
    ],
    "search_retrieval_ranking": [
        "search engineer",
        "retrieval",
        "ranking",
        "recommendation",
        "information retrieval",
        "ir engineer",
        "relevance",
    ],
    "data_scientist": ["data scientist", "research scientist"],
    "data_engineer": ["data engineer", "analytics engineer", "etl"],
    "backend_engineer": ["backend engineer", "software engineer", "platform engineer"],
    "non_technical": [
        "hr manager",
        "accountant",
        "content writer",
        "graphic designer",
        "sales executive",
        "customer support",
        "civil engineer",
        "mechanical engineer",
        "marketing manager",
        "operations manager",
        "business analyst",
        "project manager",
    ],
}

MUST_HAVE_SKILL_CLUSTERS: dict[str, list[str]] = {
    "production_ml": [
        "production ml",
        "production machine learning",
        "ml in production",
        "ship",
        "deploy",
        "serving",
        "mlops",
        "bentoml",
        "triton",
    ],
    "embeddings": [
        "embedding",
        "vector",
        "dense retrieval",
        "semantic search",
        "sentence transformer",
        "faiss",
        "milvus",
        "pinecone",
        "weaviate",
    ],
    "hybrid_retrieval": [
        "hybrid retrieval",
        "bm25",
        "lexical",
        "sparse retrieval",
        "dense recall",
        "vector search",
        "elasticsearch",
    ],
    "learning_to_rank": [
        "learning to rank",
        "learning-to-rank",
        "ltr",
        "ranking model",
        "xgboost",
        "lightgbm",
        "lambdamart",
    ],
    "evaluation": [
        "ndcg",
        "mrr",
        "recall@",
        "offline evaluation",
        "online evaluation",
        "a/b test",
        "ab test",
        "eval framework",
        "calibrat",
    ],
    "python_ml_stack": [
        "python",
        "pytorch",
        "tensorflow",
        "scikit-learn",
        "sklearn",
        "pandas",
        "numpy",
    ],
    "search_ir": [
        "information retrieval",
        "search engine",
        "retrieval",
        "recommendation system",
        "ranking",
        "relevance",
    ],
    "llm_rag": [
        "rag",
        "retrieval augmented",
        "llm",
        "fine-tuning",
        "fine tuning",
        "prompt",
    ],
}

SOFT_SIGNAL_PATTERNS: dict[str, list[str]] = {
    "ownership": [
        "own",
        "owned",
        "ownership",
        "end-to-end",
        "end to end",
        "lead",
        "led",
        "drove",
        "built from scratch",
    ],
    "shipping_speed": [
        "ship",
        "shipped",
        "shipping",
        "6 weeks",
        "fast iteration",
        "working v1",
        "prototype to production",
        "productionize",
    ],
    "cross_functional": [
        "cross-functional",
        "cross functional",
        "product manager",
        "pm ",
        "stakeholder",
        "partner with",
        "collaborat",
    ],
    "pragmatism": [
        "tradeoff",
        "trade-off",
        "pragmatic",
        "classical ir",
        "offline metrics",
        "rigorous eval",
    ],
}

ML_IR_TITLE_KEYWORDS: list[str] = [
    "machine learning",
    "ml engineer",
    "ai engineer",
    "nlp",
    "data scientist",
    "applied scientist",
    "recommendation",
    "search",
    "retrieval",
    "ranking",
    "information retrieval",
]

TECHNICAL_DESCRIPTION_KEYWORDS: list[str] = [
    "embedding",
    "vector",
    "retrieval",
    "ranking",
    "model",
    "pipeline",
    "feature",
    "xgboost",
    "lightgbm",
    "pytorch",
    "tensorflow",
    "spark",
    "kafka",
    "api",
    "kubernetes",
    "aws",
    "gcp",
    "ml ",
    "machine learning",
    "deep learning",
    "nlp",
    "llm",
    "rag",
    "ndcg",
    "a/b",
]

NON_TECHNICAL_TITLE_KEYWORDS: list[str] = [
    "hr ",
    "human resources",
    "accountant",
    "content writer",
    "graphic designer",
    "sales",
    "customer support",
    "civil engineer",
    "mechanical engineer",
    "marketing manager",
    "operations manager",
]
